---
title: "topic7"
author: "Udesing Girase"
date: "2025-10-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Q1
```{r}
factorial_fun <- function(n){
  if(n==0)
    return(1)
  prod(1:n)
}
#oR
cal_fact <- function(n){
  Fact_result <- 1
  while (n>1) {Fact_result <- Fact_result*n
  n <- n-1
  }
  return(Fact_result)
}


correlation_fun <- function(x,y){
  cor(x,y,method = "pearson")
  cor(x,y,method = "spearman")
  cor(x,y,method = "kendall")
}

quadratic_fun <- function(a,b,c){
  d <- b^2-4*a*c
  if(d < 0){
    return("no real root")
  }else{
    root1 <- (-b+sqrt(d))/(2*a)
    root2 <- (-b-sqrt(d))/(2*a)
    return(c(root1,root2))
  }
}
quadratic_fun(4,5,0)

```
Q2
```{r}
datasets::mtcars

categorize_mpg <- function(mpg){
  if (mpg < 15) {
    return("Low")
  } else if (mpg >= 15 & mpg <= 22) {
    return("Medium")
  } else {
    return("High")
  }
}

sapply(mtcars$mpg, categorize_mpg)
#OR
categorize_mpg <- function(df) {
  df$mpg_category <- cut(
    df$mpg,
    breaks = c(-Inf, 15, 22, Inf),
    labels = c("Low", "Medium", "High")
  )
  return(df)
}

data_categorized <- categorize_mpg(mtcars)
head(data_categorized)


```
Q3
```{r}
set.seed(123)
sample_sizes <- c(5, 15, 25)

for (n in sample_sizes) {
  samples <- replicate(5000, rnorm(n, mean = 0, sd = 1))
  sample_means <- colMeans(samples)
  sample_vars <- apply(samples, 2, var)
  
  cat("\nSample size:", n, "\n")
  cat("Mean of sample means:", mean(sample_means), "\n")
  cat("Mean of sample variances:", mean(sample_vars), "\n\n")
}


```
Q4
```{r}
library(purrr)
library(tibble)
#i
vec <- c(seq(1,10))
square_vec <- map_dbl(vec,~.x^2);square_vec

#ii
df <- tibble(a=rnorm(10),
             b=rnorm(10),
             c=rnorm(10),
             d=rnorm(10))
map(df,~c(mean(.x),median(.x),sd(.x)))
#OR
samples <- replicate(4, rnorm(10, 0, 1), simplify = FALSE)
map(samples, ~ c(mean = mean(.x), median = median(.x), sd = sd(.x)))

#iii
data(mtcars)
map_dbl(mtcars,mean)

#iv
mu <- c(-10, 0, 10, 100)
samples_mu <- map(mu, ~ rnorm(10, mean = .x, sd = 1))
samples_mu

#v
x <- 1:5;y <- 6;10
sum_vec <- map2_dbl(x,y,~.x+.y);sum_vec

#vi
mus <- c(5,10,-3)
sigmma <- c(1,5,10)
map2(mus,sigmma,~rnorm(10,mean=.x,sd=.y))

#vii
sizes <- c(1,3,5)
argu <- list(mean=mus,
             sd=sigmma,
             n=sizes)
argu %>% 
  pmap(rnorm)
```
Q5
```{r}
library(psych)
describe(mtcars)
#or
summary(mtcars)
apply(mtcars, 2, mean)
apply(mtcars, 2, sd)
sapply(mtcars, range)

```
Q6
```{r}
library(broom)

model <- lm(mpg ~ wt + cyl, data = mtcars)
summary(model)

# Convert regression results to tidy data frame
tidy(model)
glance(model)
augment(model)

```

